### ISSUE TITLE
Not being able to use in your version of unix

### ISSUE THREAD

**Issue by GuiFermino** [velaboratory/DataFoldvr-Virtual-Reality-Point-Cloud-Annotation#1]
I've downloaded the whole git repository and tryed to open as a new unity project, however I couldn't make it work. I'm new to unity, is there any tips you could give me on what am I doing wrong?

**Comment by kjjohnsen** [comment]
Have you tried the release?  Unity can be a bit of a learning curve, but one thing you absolutely must do is use the exact version of Unity that the project specifies.  Upgrading it (especially major versions) can cause difficult-to-resolve errors.

**Comment by GuiFermino** [comment]
Thanks @kjjohnsen, I could download the release and test the executable! However I could not succesfully upload any .pcd file to open with the application. I mean, I can select in the menu and it appears a loading bar until it is fullIs there a pre-treatment I'm missing here?

Also, when I download the release of the .zip source code, to try to open in Unity and make my changes, this is the error I get allways when entering:

![image](https://github.com/user-attachments/assets/e072fbae-aa3c-4fe3-8feb-e513f2025f73)

When I click in Continue:

![image](https://github.com/user-attachments/assets/32677fb1-7746-4f90-bdf3-d562daff0f7f)

clicking in Ignore and continuing, gives me a unity environment like this, with these error messages:

![image](https://github.com/user-attachments/assets/8d63c351-78bd-4f14-820f-b74ca4d1dca9)

Also, in the Project environment I don't see the folders DataFoldvrPcx or PorjectSettings which I originally downloaded.

![image](https://github.com/user-attachments/assets/2385d156-a3a0-4f39-8558-022fd1d90285)


![image](https://github.com/user-attachments/assets/d76d6a0e-2ae7-4372-a1ec-eab4849fc3fc)

The unity version recomended by Unity Hub is 2020.3.16f1  . Should I use another one?

**Comment by kjjohnsen** [comment]
Ah, the issue seems to be a PDFViewer asset, which is from the asset store, and so can't be released here.  I'm checking if it can be deleted safely.  It's not core to the point cloud viewer, but the core application supports viewing PDFs as well.

**Comment by kjjohnsen** [comment]
@GuiFermino I made a [nopdf ](https://github.com/velaboratory/DataFoldvr-Virtual-Reality-Point-Cloud-Annotation/tree/nopdf) branch with a fix for the errors (removed the pdf viewer).  This should at least run.  You need to set a valid folder first on the VRFolderPrefab GameObject: 
![image](https://github.com/user-attachments/assets/502a78a3-0de2-4213-8819-34a885a11641)

**Comment by GuiFermino** [comment]
Nice!! This did work indeed! The only problem I face now is the PCD. I'm not being able to visualize my own point cloud data. Every time I try to import it, it just loads as a queue of points, not the same structure it is originally. Maybe I'm missing some pretreatment you used beforehand in the poin clouds. Or would you know how the information is organized in you PCD file?Could you handle me sample from the paper or any other example of point cloud which worked to open in unity? With this I would be able to treat my own data to work similarly!

**Comment by GuiFermino** [comment]
Just as an update. In the end it worked fine. My problem was that I was inputing a large point cloud, in matter of size, and there is a amplification constant (didn't find exactly where) which enlarges it even more. So it works fine for small point clouds, like the size of a plant or somethinf around one 1x1x1 m.
